export default {
  login: 'andriod2/auth/validate',
  scanBarcode: 'reports/stock-search-barcode?stockId=',
  priceReport: 'reports/price-list',
  stockReport: 'reports/stock-balance',
  salesReport: 'reports/sales',
  sales2Report: 'reports/sales-2',
  salesAnalystReport: 'reports/sales-analyst',
  salesAnalyst2Report: 'reports/sales-analyst-2',
  purchaseReport: 'reports/purchase',
  purchaseNoDiscReport: 'reports/purchase-no-disc', 
  purchaseAnalystReport: 'reports/purchase-analyst',
  purchaseAnalystNoDiscReport: 'reports/purchase-analyst-no-disc', 
  cashDrawerReport: 'reports/cash-drawer',
  cashDrawerDetailReport: 'reports/cash-drawer-detail',
  fetchDatabases: 'schemaInfo/database-list',
  fetchStocks: 'schemaInfo/stock-group-list',
  fetchWarehouses: 'schemaInfo/ware-house-list',
};
